### PR TITLE
Spotify button

### PR DESCRIPTION
**Pull request by praneershrest**
Not really a button! Made a component for "Listen on Spotify" using an <a> tag.

### CODE REVIEW

**Comment by alikhamesy** [comment]
Although the spotify button is only seen once on the current design iteration, it would be smart to make it into a generic button component that takes in the img and txt. 
Also 2 notes: 
1. Make sure you are PRing merges into Dev and not Master
2. Make sure you are branching from Dev when making new branches, or else you'll be carrying over a lot of unrelated code (like all the svgs)

**Comment by praneershrest** [comment]
How do I request the commit to be applied to dev?

**Comment by alikhamesy** [comment]
> How do I request the commit to be applied to dev?

at the top if you click the edit button
image
then click the drop down and change it
image
and finally click save

**Review by alikhamesy — CHANGES_REQUESTED** [review]
I dont think the component `SpotifyButton` should be a thing, since we can just instantiate that button in the Home page.

Also can you double check that the font-weight is supposed to be 550 and not 600?

**Comment by praneershrest** [comment]
> I dont think the component `SpotifyButton` should be a thing, since we can just instantiate that button in the Home page.
> 
> Also can you double check that the font-weight is supposed to be 550 and not 600?

Should I just delete the SpotifyButton component and call it in the Homepage component? For the font it says semi-bold (is that 600)?

**Comment by alikhamesy** [comment]
> Should I just delete the SpotifyButton component and call it in the Homepage component? For the font it says semi-bold (is that 600)?

Yeah I say just delete it, and semi-bold is 600 according to figam's Code tab.

**Review by alikhamesy — DISMISSED** [review]

**Review by alikhamesy — APPROVED** [review]

**Pull request merged**
